version: "3"

services:
  tinyurl:
    build: .
    image: hadis/tinyurl:latest
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=hadis
      - MARIADB_PASSWORD=hadis-password
      - MARIADB_ROOT_PASSWORD=hadis-root-password
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"
